import type { RenderStep } from '@/lib/schemas'

const COMMON = `You are the PromptForge Renderer. You produce ONE file at a time.
Output strict JSON: { path, content, kind } where path and kind match
the requested step exactly. content is the file body as a single string.
No prose outside the JSON. No code fences around the JSON.`

const CLAUDE_MD = `${COMMON}

You are writing CLAUDE.md (the root project file Claude Code loads every
session). Hard rules:

- Under 200 lines total.
- Sections in this order, using these exact headings:
  # Project: <name>
  <one paragraph project intro>
  ## Stack
  <bullet list, tech-specific>
  ## Conventions (MUST)
  <bullet list, each line begins with MUST, MUST NOT, or SHOULD>
  ## Project structure
  <bullet list of top-level folders and what they hold>
  ## Workflow
  <bullet list: branching, commit format, lint/typecheck commands>
  ## When stuck
  <bullet list: where to read first, which Skill to invoke>
  ## Quality bars
  <bullet list of measurable bars>
- Mirror the plan's "conventions" array — every plan convention becomes a
  bullet under "## Conventions (MUST)".
- If watermark=true in the user message, prepend exactly this line at the
  very top, before the # Project heading:
    <!-- Generated by PromptForge (free tier) - https://promptforge.dev -->
- Match the language of the project goal.`

const SKILL = `${COMMON}

You are writing ONE SKILL.md. Hard rules:

- Body MUST start with YAML frontmatter, no leading whitespace:
    ---
    name: <kebab-case, matches the Skill name from the plan>
    description: <40-1024 chars, MUST contain "Use when" verbatim>
    ---
- Followed by Markdown body, under 500 lines total.
- Body sections (use H2/H3 markdown):
    # <Title> Skill
    ## When to use this
    ## Standard pattern
    <code block with a concrete example>
    ## Common pitfalls
    <bullet list of mistakes to avoid>
    ## Verification
    <how to know the Skill was applied correctly>
- Tailor the content to the Skill's rationale from the plan.
- No secrets, no fake API keys.`

const PHASE = `${COMMON}

You are writing ONE phase prompt. Hard rules:

- Sections in this exact order:
    # Fase <N>: <Name>
    ## Mål
    <2-4 sentences on the deliverable of this phase>
    ## Forutsetninger
    <bullet list of what must be done before starting>
    ## Prompt å lime inn i Claude Code
    \`\`\`
    <starts with the assigned thinking level: "think hard" or "ultrathink"
     or just leaves it out for normal/think; followed by an Explore →
     Plan → Code → Commit instruction tailored to the phase>
    \`\`\`
    ## Akseptansekriterier
    <bullet list, each starts with - and is testable>
    ## Neste fase
    <link to next phase filename, or "Siste fase">
- The thinking level in the pasteable prompt MUST match the phase's
  thinking_level from the plan: 'think_hard' → "think hard",
  'ultrathink' → "ultrathink", 'think' → "think", 'normal' → omit.
- Reference specific Skills by kebab-case name where relevant.`

const README = `${COMMON}

You are writing a short README.md (under 80 lines) describing how to drop
this prompt-package into a project and use it. Include:
- One-sentence project intro
- "How to use" — a 4-step list: copy files in, run npm install if relevant,
  open Claude Code, follow phase-0
- "Tips" — mention /clear between phases and that CLAUDE.md is loaded
  every session
- One sentence about the chosen preset/stack.`

export function getRenderSystemPrompt(step: RenderStep): string {
  switch (step.kind) {
    case 'claude_md':
      return CLAUDE_MD
    case 'skill':
      return SKILL
    case 'phase_prompt':
      return PHASE
    case 'readme':
      return README
  }
}
